Update cmake-single-platform.yml

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -40,7 +40,7 @@ jobs:
       with:
         # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
         python-version: "3.9"
-              
+
     - name: Get Conan
       # You may pin to the exact commit or the version.
       # uses: turtlebrowser/get-conan@c171f295f3f507360ee018736a6608731aa2109d
@@ -58,8 +58,7 @@ jobs:
         cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
         # The name of the workflow preset. Optional, it cannot be used with any other preset input. This value is stored in the WORKFLOW_PRESET_NAME environment variable, and used by the default value of 'workflowPresetCmdString' input.
         configurePreset: "ninja-conan-release"
-          
-                    
+
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
@@ -69,4 +68,10 @@ jobs:
       working-directory: ${{github.workspace}}/build/release
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}}
+      run: |
+        if [ -f "Ciple-Framework" ]; then
+          echo "Ciple-Framework exists. Running tests..."
+        else
+          echo "Error: Ciple-Framework not found!"
+          exit 1
+        fi
